version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
      # Initializer
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/Application.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/ServletInitializer.class'
      # Config
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/AppConfig.class'
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/MvcConfig.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/WebSecConfig.class'
      # POJOs
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/Appointment.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/AppointmentRepository.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/User.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/UserRepository.class'
      # Controllers
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/SchedulerController.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/ServicesController.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/ErrorController.class'
    - 'ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/UserController.class'
      # Static Resources
    - 'ROOT/WEB-INF/classes/static/resources/**/*'
#    - 'ROOT/WEB-INF/classes/static/resources/js/*'
#    - 'ROOT/WEB-INF/classes/static/resources/styles/*'
      # Templates
    - 'ROOT/WEB-INF/classes/templates/*'
      # Project JAR files
    - 'ROOT/WEB-INF/lib/**/*'
#    - 'ROOT/WEB-INF/lib/antlr-2.7.7.jar'
#    - 'ROOT/WEB-INF/lib/aspectjweaver-1.8.13.jar'
#    - 'ROOT/WEB-INF/lib/attoparser-2.0.4.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/classmate-1.3.4.jar'
#    - 'ROOT/WEB-INF/lib/dom4j-1.6.1.jar'
#    - 'ROOT/WEB-INF/lib/hibernate-commons-annotations-5.0.1.Final.jar'
#    - 'ROOT/WEB-INF/lib/hibernate-core-5.2.17.Final.jar'
#    - 'ROOT/WEB-INF/lib/hibernate-jpa-2.1-api-1.0.2.Final.jar'
#    - 'ROOT/WEB-INF/lib/hibernate-validator-6.0.10.Final.jar'
#    - 'ROOT/WEB-INF/lib/HikariCP-2.7.9.jar'
#    - 'ROOT/WEB-INF/lib/jackson-annotations-2.9.0.jar'
#    - 'ROOT/WEB-INF/lib/jackson-core-2.9.6.jar'
#    - 'ROOT/WEB-INF/lib/jackson-databind-2.9.6.jar'
#    - 'ROOT/WEB-INF/lib/jackson-datatype-jdk8-2.9.6.jar'
#    - 'ROOT/WEB-INF/lib/jackson-datatype-jsr310-2.9.6.jar'
#    - 'ROOT/WEB-INF/lib/jackson-module-parameter-names-2.9.6.jar'
#    - 'ROOT/WEB-INF/lib/jandex-2.0.3.Final.jar'
#    - 'ROOT/WEB-INF/lib/javassist-3.22.0-GA.jar'
#    - 'ROOT/WEB-INF/lib/javax.annotation-api-1.3.2.jar'
#    - 'ROOT/WEB-INF/lib/javax.transaction-api-1.2.jar'
#    - 'ROOT/WEB-INF/lib/jboss-logging-3.3.2.Final.jar'
#    - 'ROOT/WEB-INF/lib/jul-to-slf4j-1.7.25.jar'
#    - 'ROOT/WEB-INF/lib/log4j-api-2.10.0.jar'
#    - 'ROOT/WEB-INF/lib/log4j-to-slf4j-2.10.0.jar'
#    - 'ROOT/WEB-INF/lib/logback-classic-1.2.3.jar'
#    - 'ROOT/WEB-INF/lib/logback-core-1.2.3.jar'
#    - 'ROOT/WEB-INF/lib/mysql-connector-java-5.1.46.jar'
#    - 'ROOT/WEB-INF/lib/slf4j-api-1.7.25.jar'
#    - 'ROOT/WEB-INF/lib/snakeyaml-1.19.jar'
#    - 'ROOT/WEB-INF/lib/spring-aop-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-aspects-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-beans-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-autoconfigure-2.0.3.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-boot-devtools-2.0.2.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-2.0.3.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-boot-starter-data-rest-2.0.2.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-aop-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-data-jpa-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-jdbc-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-json-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-logging-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-security-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-thymeleaf-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-tomcat-2.0.3.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-boot-starter-web-2.0.3.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-context-5.0.6.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-core-5.0.6.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-data-commons-2.0.7.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-data-rest-core-3.0.7.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-data-rest-webmvc-3.0.7.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-expression-5.0.6.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-hateoas-0.24.0.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-jcl-5.0.6.RELEASE.jar'
#    #- 'ROOT/WEB-INF/lib/spring-plugin-core-1.2.0.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-context-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-core-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-data-commons-2.0.8.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-data-jpa-2.0.8.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-expression-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-jcl-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-jdbc-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-orm-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-security-config-5.0.6.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-security-core-5.0.6.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-security-web-5.0.6.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-tx-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-web-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/spring-webmvc-5.0.7.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/thymeleaf-3.0.9.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/thymeleaf-extras-java8time-3.0.1.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/thymeleaf-spring5-3.0.9.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/tomcat-embed-core-8.5.31.jar'
#    - 'ROOT/WEB-INF/lib/tomcat-embed-el-8.5.31.jar'
#    - 'ROOT/WEB-INF/lib/tomcat-embed-websocket-8.5.31.jar'
#    - 'ROOT/WEB-INF/lib/unbescape-1.1.5.RELEASE.jar'
#    - 'ROOT/WEB-INF/lib/validation-api-2.0.1.Final.jar'